hp:
  wait:
    - 1
    - 2
    - 5
meta:
  gpus: 5 
  key:
    - wait
  mode: nni 
  prefix: demo_nni
  repeat: 1
  sample: 20
  script: 'python main_metrics.py'
  port: 8082
sbatch:
  mem: 16G
nni:
  authorName: Hao
  experimentName: 'Demo HP search experiments'
  maxExecDuration: 2h
  maxTrialNum: 50
  trialConcurrency: 12
  tuner:
    builtinTunerName: TPE
    classArgs:
      optimize_mode: maximize
  useAnnotation: false 

