hp:
  wait:
    - 1
    - 2
    - 5
meta:
  gpus: 1
  key:
    - wait
  metrics_path: ~/.launchpad/{exp_name}/metrics.csv
  mode: grid
  prefix: demo_metrics
  repeat: 1
  sample: 20
  script: 'python main_metrics.py'
sbatch:
  mem: 16G
