meta:
    script: python main_metrics.py
    mode: grid 
    sample: 20
    prefix: demo_metrics
    repeat: 1
    gpus: 1
    metrics_path: ~/.launchpad/{exp_name}/metrics.csv
    key: ['wait']
    
hp: 
    wait: [1, 2, 5, 10]

sbatch:
    mem: 16G      
