hp:
  wait:
    - 20
    - 30
    - 50
meta:
  gpus: 5
  key:
    - wait
  prefix: demo_nni
  repeat: 1
  sample: 20
  script: 'python main_nni.py'
  port: 8082
sbatch:
  mem: 16G
  exclude: deep[21-25]
nni:
  authorName: Hao
  experimentName: 'Demo HP search experiments'
  maxExecDuration: 2h
  maxTrialNum: 50
  trialConcurrency: 12
  tuner:
    builtinTunerName: TPE
    classArgs:
      optimize_mode: maximize
  useAnnotation: false
